# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XDEShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XDEShop

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'FMDB', '~> 2.7.2'

pod 'Masonry', '~> 1.0.2'
pod 'SDCycleScrollView', '~> 1.66'
pod 'SDWebImage', '~> 4.2.2'
pod 'IQKeyboardManager', '~> 5.0.7'

pod 'YYCache', '~> 1.0.4'

end
